-- Comment template pool (400 total)
-- General (200)
INSERT INTO comment_templates (category, content) VALUES
('general', '🔥🔥🔥'),
('general', 'This is amazing!'),
('general', 'Love this so much'),
('general', 'Wow 😍'),
('general', 'Absolutely stunning'),
('general', 'Goals!'),
('general', 'Can''t stop looking at this'),
('general', 'You''re killing it'),
('general', 'This made my day'),
('general', 'So good!!'),
('general', 'Incredible shot'),
('general', 'Obsessed'),
('general', 'Yes yes yes'),
('general', 'Perfection'),
('general', 'Need more of this'),
('general', 'Iconic'),
('general', 'Chef''s kiss 👌'),
('general', 'Living for this'),
('general', 'Main character energy'),
('general', 'Slay'),
('general', 'No notes'),
('general', '10/10'),
('general', 'This is everything'),
('general', 'Stunning as always'),
('general', 'You never miss'),
('general', 'Another banger'),
('general', 'How do you do it'),
('general', 'Teach me your ways'),
('general', 'Saved this immediately'),
('general', 'Sharing with everyone'),
('general', 'This deserves more likes'),
('general', 'Underrated post'),
('general', 'Peak content'),
('general', 'Elite'),
('general', 'Certified classic'),
('general', 'Hall of fame material'),
('general', 'Instant follow'),
('general', 'You''re going places'),
('general', 'Big things coming'),
('general', 'Keep going'),
('general', 'So inspiring'),
('general', 'Made me smile'),
('general', 'Needed this today'),
('general', 'Pure vibes'),
('general', 'Mood'),
('general', 'Same energy'),
('general', 'Relatable'),
('general', 'This hits different'),
('general', 'No cap'),
('general', 'Facts'),
('general', 'Real talk'),
('general', 'So true'),
('general', 'Couldn''t agree more'),
('general', 'Well said'),
('general', 'Beautifully captured'),
('general', 'Art'),
('general', 'Masterpiece'),
('general', 'Gallery worthy'),
('general', 'Frame this'),
('general', 'Print this'),
('general', 'Wallpaper material'),
('general', 'Screenshot saved'),
('general', 'Bookmarked'),
('general', 'Following for more'),
('general', 'Can''t wait for the next one'),
('general', 'When''s the next post'),
('general', 'More please'),
('general', 'We need a part 2'),
('general', 'This series is fire'),
('general', 'Your best yet'),
('general', 'Top tier'),
('general', 'Next level'),
('general', 'Unreal'),
('general', 'Mind blown'),
('general', 'Speechless'),
('general', 'Wow just wow'),
('general', 'Okay but this'),
('general', 'Wait this is so good'),
('general', 'Hold up'),
('general', 'Pause'),
('general', 'Let me process this'),
('general', 'Still thinking about this'),
('general', 'Came back to like again'),
('general', 'Double tap worthy'),
('general', 'Triple tap if I could'),
('general', 'Heart eyes'),
('general', '😍😍😍'),
('general', '❤️❤️❤️'),
('general', '👏👏👏'),
('general', '🙌'),
('general', '💯'),
('general', '✨✨'),
('general', '🌟'),
('general', '💫'),
('general', '🔥'),
('general', '💕'),
('general', '😊'),
('general', '🤩'),
('general', '👀'),
('general', '🙏'),
('general', '💪'),
('general', '🎉'),
('general', 'So aesthetic'),
('general', 'Vibes are immaculate'),
('general', 'Clean'),
('general', 'Crisp'),
('general', 'Sharp'),
('general', 'Bold'),
('general', 'Unique'),
('general', 'Original'),
('general', 'Creative'),
('general', 'Innovative'),
('general', 'Fresh'),
('general', 'Different'),
('general', 'Standout'),
('general', 'Memorable'),
('general', 'Unforgettable'),
('general', 'Legendary'),
('general', 'Historic'),
('general', 'Moment'),
('general', 'Era'),
('general', 'Culture'),
('general', 'Movement'),
('general', 'Trendsetter'),
('general', 'Ahead of the curve'),
('general', 'Visionary'),
('general', 'Genius'),
('general', 'Brilliant'),
('general', 'Smart'),
('general', 'Clever'),
('general', 'Witty'),
('general', 'Funny'),
('general', 'Made me laugh'),
('general', 'LOL'),
('general', 'Dead 💀'),
('general', 'I''m crying'),
('general', 'Too good'),
('general', 'Can''t handle this'),
('general', 'Stop being so talented'),
('general', 'Unfair advantage'),
('general', 'How is this free'),
('general', 'Premium content'),
('general', 'Worth the follow'),
('general', 'Best on my feed today'),
('general', 'Feed is blessed'),
('general', 'Algorithm did good'),
('general', 'Glad I found you'),
('general', 'Hidden gem'),
('general', 'About to blow up'),
('general', 'Pre-famous'),
('general', 'Remember this post'),
('general', 'Screenshot for the archives'),
('general', 'This will age well'),
('general', 'Timeless'),
('general', 'Classic'),
('general', 'Evergreen'),
('general', 'Always relevant'),
('general', 'Still hits'),
('general', 'Age like fine wine'),
('general', 'Gets better every time'),
('general', 'New favorite'),
('general', 'All time favorite'),
('general', 'Top 5 post'),
('general', 'Best of the year'),
('general', 'Award worthy'),
('general', 'Nomination incoming'),
('general', 'Trophy emoji soon'),
('general', 'Champion'),
('general', 'Winner'),
('general', 'Victory lap'),
('general', 'Crowned'),
('general', 'Royalty'),
('general', 'King/Queen behavior'),
('general', 'Boss move'),
('general', 'Power move'),
('general', 'Big energy'),
('general', 'Confidence level 100'),
('general', 'Self love'),
('general', 'Glow up'),
('general', 'Transformation'),
('general', 'Evolution'),
('general', 'Growth'),
('general', 'Progress'),
('general', 'Journey'),
('general', 'Story'),
('general', 'Chapter'),
('general', 'Plot twist'),
('general', 'Cliffhanger'),
('general', 'To be continued'),
('general', 'Stay tuned'),
('general', 'Don''t stop'),
('general', 'Never stop'),
('general', 'Keep creating'),
('general', 'Keep sharing'),
('general', 'World needs this'),
('general', 'Thank you for posting'),
('general', 'Grateful'),
('general', 'Appreciate you'),
('general', 'Support always'),
('general', 'Here for it'),
('general', 'Ride or die'),
('general', 'Day one energy'),
('general', 'OG fan'),
('general', 'Since the beginning'),
('general', 'Watching you grow'),
('general', 'Proud of you'),
('general', 'You did that'),
('general', 'Period.'),
('general', 'End of discussion'),
('general', 'Case closed'),
('general', 'Mic drop'),
('general', 'That''s all folks');

-- Selfie (50)
INSERT INTO comment_templates (category, content) VALUES
('selfie', 'You''re glowing! ✨'),
('selfie', 'That skin though'),
('selfie', 'Hair goals'),
('selfie', 'Perfect angle'),
('selfie', 'Selfie queen'),
('selfie', 'Selfie king'),
('selfie', 'Natural beauty'),
('selfie', 'No filter needed'),
('selfie', 'Camera loves you'),
('selfie', 'Model material'),
('selfie', 'Strike a pose'),
('selfie', 'Serving looks'),
('selfie', 'Face card never declines'),
('selfie', 'Photogenic af'),
('selfie', 'Mirror who'),
('selfie', 'Front camera legend'),
('selfie', 'That smile 😊'),
('selfie', 'Eyes are mesmerizing'),
('selfie', 'Confidence is showing'),
('selfie', 'Main character selfie'),
('selfie', 'Profile pic worthy'),
('selfie', 'New pfp alert'),
('selfie', 'How are you real'),
('selfie', 'Beauty standard'),
('selfie', 'Glow up confirmed'),
('selfie', 'Radiating'),
('selfie', 'Sunshine personified'),
('selfie', 'Lighting on point'),
('selfie', 'Golden hour vibes'),
('selfie', 'Soft glam'),
('selfie', 'Effortless'),
('selfie', 'Born ready'),
('selfie', 'Picture perfect'),
('selfie', 'Flawless'),
('selfie', 'Stunning features'),
('selfie', 'That jawline'),
('selfie', 'Cheekbones for days'),
('selfie', 'Lips look amazing'),
('selfie', 'Brows on fleek'),
('selfie', 'Makeup or natural? Either way wow'),
('selfie', 'Self care showing'),
('selfie', 'Well rested energy'),
('selfie', 'Happy looks good on you'),
('selfie', 'Joy is contagious'),
('selfie', 'Positive vibes'),
('selfie', 'Infectious smile'),
('selfie', 'Can''t look away'),
('selfie', 'Magnetic'),
('selfie', 'Star quality'),
('selfie', 'Red carpet ready');

-- Food (50)
INSERT INTO comment_templates (category, content) VALUES
('food', 'I''m hungry now 😋'),
('food', 'Recipe please!'),
('food', 'That looks delicious'),
('food', 'Need to try this'),
('food', 'Foodie heaven'),
('food', 'Mouth watering'),
('food', 'Chef mode activated'),
('food', 'Homemade hits different'),
('food', 'Restaurant quality'),
('food', 'Plating is art'),
('food', 'Instagram vs reality but this is both'),
('food', 'Food porn'),
('food', 'Drooling'),
('food', 'Take my money'),
('food', 'Where is this'),
('food', 'Adding to my list'),
('food', 'Comfort food'),
('food', 'Soul food'),
('food', 'Perfect bite'),
('food', 'Crispy looks crispy'),
('food', 'That cheese pull though'),
('food', 'Portion size approved'),
('food', 'Worth every calorie'),
('food', 'No regrets'),
('food', 'Diet starts tomorrow'),
('food', 'Cheat day earned'),
('food', 'Brunch goals'),
('food', 'Dinner is served'),
('food', 'Late night snack vibes'),
('food', 'Coffee and this = perfect morning'),
('food', 'Sweet tooth satisfied'),
('food', 'Savory perfection'),
('food', 'Fresh ingredients showing'),
('food', 'Farm to table energy'),
('food', 'Street food elite'),
('food', 'Fine dining at home'),
('food', 'Meal prep king/queen'),
('food', 'Cooking skills on display'),
('food', 'Teach me'),
('food', 'Cookbook when'),
('food', 'Food blogger material'),
('food', 'Yelp review: 5 stars'),
('food', 'Michelin star vibes'),
('food', 'Secret ingredient?'),
('food', 'Grandma approved'),
('food', 'Tradition meets innovation'),
('food', 'Fusion done right'),
('food', 'Spicy looks spicy 🌶️'),
('food', 'Healthy but make it tasty'),
('food', 'Balanced plate');

-- Landscape (50)
INSERT INTO comment_templates (category, content) VALUES
('landscape', 'Breathtaking view'),
('landscape', 'Nature is undefeated'),
('landscape', 'Wanderlust activated'),
('landscape', 'Take me there'),
('landscape', 'Travel goals'),
('landscape', 'Bucket list add'),
('landscape', 'Paradise found'),
('landscape', 'Earth is beautiful'),
('landscape', 'Sky colors are insane'),
('landscape', 'Golden hour perfection'),
('landscape', 'Blue hour magic'),
('landscape', 'Mountains are calling'),
('landscape', 'Ocean therapy'),
('landscape', 'Forest bathing'),
('landscape', 'Desert vibes'),
('landscape', 'City skyline iconic'),
('landscape', 'Urban explorer'),
('landscape', 'Hidden gem location'),
('landscape', 'Off the beaten path'),
('landscape', 'Adventure awaits'),
('landscape', 'Road trip essential'),
('landscape', 'Camping spot found'),
('landscape', 'Sunrise chaser'),
('landscape', 'Sunset lover'),
('landscape', 'Clouds look painted'),
('landscape', 'Reflection perfection'),
('landscape', 'Symmetry goals'),
('landscape', 'Leading lines master'),
('landscape', 'Composition chef kiss'),
('landscape', 'National geographic worthy'),
('landscape', 'Postcard material'),
('landscape', 'Desktop wallpaper'),
('landscape', 'Peaceful'),
('landscape', 'Serene'),
('landscape', 'Meditative'),
('landscape', 'Escape reality'),
('landscape', 'Digital detox spot'),
('landscape', 'Silence is golden'),
('landscape', 'Raw beauty'),
('landscape', 'Untouched'),
('landscape', 'Wild and free'),
('landscape', 'Season perfect'),
('landscape', 'Weather cooperated'),
('landscape', 'Right place right time'),
('landscape', 'Lucky shot'),
('landscape', 'Patience paid off'),
('landscape', 'Early bird gets the photo'),
('landscape', 'Drone shot?'),
('landscape', 'Telephoto compression'),
('landscape', 'Wide angle wonder');

-- Sport (50)
INSERT INTO comment_templates (category, content) VALUES
('sport', 'Beast mode 💪'),
('sport', 'No days off'),
('sport', 'Grind never stops'),
('sport', 'Dedication showing'),
('sport', 'Hard work pays off'),
('sport', 'Gains visible'),
('sport', 'PR incoming'),
('sport', 'New personal best'),
('sport', 'Form is perfect'),
('sport', 'Technique on point'),
('sport', 'Coach approved'),
('sport', 'Athlete mentality'),
('sport', 'Champion mindset'),
('sport', 'Training arc'),
('sport', 'Off season work'),
('sport', 'Game day ready'),
('sport', 'Match winner energy'),
('sport', 'Clutch performance'),
('sport', 'MVP vibes'),
('sport', 'Hall of fame play'),
('sport', 'Highlight reel'),
('sport', 'Sports center top 10'),
('sport', 'Unstoppable'),
('sport', 'Dominant'),
('sport', 'Competitive fire'),
('sport', 'Never give up'),
('sport', 'Comeback season'),
('sport', 'Underdog story'),
('sport', 'Against all odds'),
('sport', 'Heart of a champion'),
('sport', 'Team player'),
('sport', 'Leadership showing'),
('sport', 'Inspiring the next gen'),
('sport', 'Role model'),
('sport', 'Discipline > motivation'),
('sport', 'Consistency wins'),
('sport', '1% better every day'),
('sport', 'Recovery is part of training'),
('sport', 'Mind muscle connection'),
('sport', 'Explosive power'),
('sport', 'Endurance beast'),
('sport', 'Speed demon'),
('sport', 'Agility goals'),
('sport', 'Flexibility impressive'),
('sport', 'Core strength'),
('sport', 'Full body workout'),
('sport', 'Cardio king/queen'),
('sport', 'Lift heavy'),
('sport', 'Run far'),
('sport', 'Play hard');
